import { tailwind } from '@theme-ui/presets'

const theme = {
  ...tailwind,
  initialColorModeName: `light`,
  colors: {
    ...tailwind.colors,
    primary: tailwind.colors.red[7],
    secondary: tailwind.colors.blue[7],
    background: tailwind.colors.gray[1],
    modes: {
      dark: {
        text: tailwind.colors.white,
        primary: tailwind.colors.pink[4],
        background: tailwind.colors.gray[8],
        textMuted: tailwind.colors.gray[5],
      },
    },
  },
  breakpoints: [`640px`, `768px`, `1024px`, `1280px`],
  bpDefaultIndex: 0,
  sizes: {
    ...tailwind.sizes,
    container: 1024,
    minViewport: 320,
    icon: 20,
  },
  styles: {
    ...tailwind.styles,
    root: {
      ...tailwind.styles.root,
      color: `text`,
      backgroundColor: `background`,
    },
    a: {
      color: `secondary`,
      textDecoration: `none`,
      ':hover': {
        textDecoration: `underline`,
      },
    },
  },
  fonts: {
    ...tailwind.fonts,
    body: tailwind.fonts.sans,
  },
  fontWeights: {
    ...tailwind.fontWeights,
  },
  buttons: {
    ...tailwind.buttons,
    elevatedExt: {
      py: [1, 2],
      px: [2, 3],
      my: [3, 3, 3],
      mx: [0, 3, 4, 4],
      minHeight: `44px`,
      minWidth: [`254px`, `274px`, `294px`, `354px`],
      cursor: `pointer`,
      fontSize: `100%`,
      lineHeight: `inherit`,
      backgroundColor: `gray.1`,
      borderWidth: `1px`,
      borderStyle: `solid`,
      borderColor: `gray.3`,
      color: `text`,
      fontWeight: `bold`,
      borderRadius: [0, `default`],
      boxShadow: `default`,
      '&:hover': {
        backgroundColor: `gray.2`,
      },
      '&:focus': {
        outlineColor: `blue.2`,
      },
    },
    borderedExt: {
      py: [0, 0, 1, 2],
      px: [2, 2, 2, 3],
      mb: [3, 3, 3, 3],
      mx: [0, 2, 2, 4],
      minHeight: [`44px`],
      minWidth: [`270px`, `220px`, `240px`, `270px`],
      cursor: `pointer`,
      fontSize: `100%`,
      lineHeight: `inherit`,
      backgroundColor: `gray.1`,
      borderTopWidth: `1px`,
      borderLeftWidth: [`1px`, `1px`],
      borderBottomWidth: `1px`,
      borderRightWidth: [`1px`, `1px`],
      borderStyle: `solid`,
      borderColor: `gray.6`,
      color: `text`,
      fontWeight: `bold`,
      borderRadius: [`default`],
      '&:hover': {
        backgroundColor: `gray.2`,
      },
      '&:focus': {
        outlineColor: `blue.2`,
      },
    },
  },
  texts: {
    elevated: {
      p: [2, 3],
      textAlign: `center`,
      color: `gray.8`,
      fontSize: [1, 2, 2],
      fontFamily: `lato, ${tailwind.fonts.sans}`,
      fontWeight: tailwind.fontWeights.bold,
    },
  },
  links: {
    innerButtonLink: {
      transition: `all 0.2s ease-in-out`,
      color: `gray.7`,
      fontSize: [2, 2],
      fontFamily: `lato, ${tailwind.fonts.sans}`,
      fontWeight: tailwind.fontWeights.normal,
      textDecoration: `none`,
      ':hover': {
        color: `blue.6`,
        textDecoration: `none`,
      },
    },
  },
  logo: {
    inNavbar: {
      mt: `20px`,
      ml: 3,
      minWidth: 100,
      maxWidth: 150,
      display: [`none`, `block`],
      width: [`auto`, 150],
      filter: `invert(0) sepia(0) saturate(0) hue-rotate(0deg)`,
    },
    inHeader: {
      minWidth: 200,
      maxWidth: 400,
      width: [200, 300, 350, 400],
      filter: `invert(1) sepia(1) saturate(0) hue-rotate(0deg)`,
    },
  },
  parallax: {
    heightHeader: [`45vh`, `55vh`, `70vh`, `70vh`],
    heightMain: [`40vh`, `55vh`, `70vh`, `70vh`],
    heightFooter: [`50vh`, `75vh`, `80vh`, `85vh`],
    parallaxInner: {
      flexDirection: [`column`, `row`],
      justifyContent: `space-around`,
      height: `auto`,
      maxHeight: `400px`,
      width: [`auto`, `auto`],
      maxWidth: `1100px`,
      position: `absolute`,
      top: [`50%`, `50%`, `50%`],
      left: [`50%`, `50%`, `50%`],
      transform: `translate(-50%,-50%)`,
    },
    parallaxInnerMap: {
      flexDirection: [`column`],
      justifyContent: `center`,
      alignItems: `stretch`,
      height: `auto`,
      maxHeight: `500px`,
      maxWidth: `100%`,
      position: `absolute`,
      top: [`50%`, `50%`, `50%`],
      left: [`50%`, `50%`, `50%`],
      transform: `translate(-50%,-50%)`,
    },
    parallaxInnerTop: {
      flexDirection: [`column`],
      justifyContent: `space-between`,
      alignItems: `center`,
      height: `100%`,
      width: `100%`,
      maxHeight: `100%`,
      maxWidth: `100%`,
      position: `absolute`,
      top: 0,
      left: 0,
      transform: `translate(0%,0%)`,
    },
  },
  flagDropDown: {
    selectedSize: 16,
    optionsSize: 16,
  },
  navbar: {
    height: `84px`,
    main: {
      minHeight: `84px`,
      width: `100%`,
      height: `auto`,
      bg: `rgba(237, 242, 247, 0.8)`,
      position: `fixed`,
      top: 0,
      zIndex: 9999,
    },
    scrolloffset: {
      scrollPaddingTop: `54px`,
    },
    flexcolumn: {
      mt: 0,
      p: 1,
      flexDirection: `column`,
      justifyContent: `space-around`,
      flexWrap: `no-wrap`,
      flexGrow: 0,
      flexBasis: `auto`,
    },
    flexrow: {
      flexDirection: `row`,
      flexWrap: [`no-wrap`, `wrap`],
      flexGrow: 0,
      flexBasis: `auto`,
    },
    boxcolumn: {
      ml: `auto`,
      width: `100%`,
      height: `auto`,
    },
    boxrow: {
      mt: [2, 2, 2],
      mr: [1, 3, 4],
      pt: [3, 2, 2],
    },
    boxrowFlag: {
      mt: [2, 2, 2],
      mr: [1, 2, 2],
      pt: [3, 2, 2],
    },
    navlink: {
      px: 1,
      fontSize: [1, 2, 3],
      fontFamily: `lato, ${tailwind.fonts.sans}`,
      fontWeight: tailwind.fontWeights.bold,
    },
    navlinkactive: {
      px: 1,
      fontSize: [1, 2, 3],
      fontFamily: `lato, ${tailwind.fonts.sans}`,
      fontWeight: tailwind.fontWeights.bold,
      borderBottom: `3px solid`,
      borderRadius: `0px`,
      borderColor: `primary`,
      color: `primary`,
    },
    navLinkActiveClass: {
      px: 1,
      borderBottom: `3px solid`,
      borderRadius: `0px`,
      borderColor: `primary`,
      color: `primary`,
    },
  },
  blog: {
    list_link: {
      px: 1,
      fontSize: [1, 2, 3],
      fontFamily: `lato, ${tailwind.fonts.sans}`,
      fontWeight: tailwind.fontWeights.bold,
      color: `primary`,
      textDecoration: `none`,
      ':hover': {
        color: `primary`,
        textDecoration: `underline`,
      },
    },
  },
  mdx: {
    boxpost: {
      p: [2, 2, 4],
      textAlign: [`left`, `left`],
      bg: tailwind.colors.gray[2],
      fontSize: [1, 2, 2],
      fontFamily: tailwind.fonts.sans,
      fontWeight: [tailwind.fontWeights.normal],
    },
    boxmain: {
      p: [2, 2, 3],
      textAlign: [`left`, `center`],
      bg: tailwind.colors.gray[1],
      fontSize: [1, 2, 2],
      fontFamily: tailwind.fonts.sans,
      fontWeight: [tailwind.fontWeights.normal],
    },
    boxprices: {
      p: [2, 2, 3],
      textAlign: `left`,
      maxWidth: 600,
      bg: tailwind.colors.gray[1],
      fontSize: [1, 2, 2],
      fontFamily: tailwind.fonts.sans,
      fontWeight: [tailwind.fontWeights.normal],
    },
  },
  contact: {
    flexButtonGroup: {
      width: `auto`,
      flexDirection: [`column`, `row`, `row`],
      justifyContent: `center`,
    },
    flexCentered: {
      width: `100%`,
      height: `100%`,
      justifyContent: `center`,
      alignItems: `center`,
    },
  },
  layout: {
    main: {
      bg: `background`,
    },
    pages: {
      bg: `gray.2`,
    },
    header: {
      width: `100%`,
      bg: tailwind.colors.gray[2],
    },
    main: {
      ...tailwind.styles.Main,
      mt: `auto`,
      width: `100%`,
      flex: `1 1 auto`,
      position: `relative`,
    },
    footer: {
      width: `100%`,
      bg: tailwind.colors.gray[2],
    },
  },
}

export default theme
